odim 74:Adding changes related to the redis stream event consuming
jeevan-kamkar/ODIM pull request #43
Opened 2022-01-05 04:48 UTC by jeevan-kamkar

2022-01-05 05:02 UTC, irappa-pattar requested changes
Minor comments, please address

2022-01-05 05:02 UTC, irappa-pattar commented on lib-messagebus/datacommunicator/redisstreamcomm.go
> +	if len(id) == 0 {
I think it will be always 0, no need to check.

2022-01-05 05:02 UTC, irappa-pattar commented on lib-messagebus/datacommunicator/redisstreamcomm.go
> +					Group:    "eventreaders_grp",
Add Group name in constants instead of hard code

2022-01-05 05:16 UTC, jeevan-kamkar commented on lib-messagebus/datacommunicator/redisstreamcomm.go
> +					Group:    "eventreaders_grp",
updated

2022-01-05 05:16 UTC, jeevan-kamkar commented on lib-messagebus/datacommunicator/redisstreamcomm.go
> +	if len(id) == 0 {
updated

2022-01-05 07:21 UTC, irappa-pattar approved these changes

2022-01-07 11:51 UTC, amar-shalgar approved these changes
LGTM

2022-01-07 12:21 UTC, merged